# [[file:vasp-server.note::*cargo.toml][cargo.toml:1]]
[package]
name = "vasp-tools"
version = "0.0.4"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
gosh = { version = ">=0.0.1", features=["adhoc"] }
nix = "0.19"
bstr = "0.2"
fs2 = "0.4"
bytes = "1"
structopt = "0.3"
tempfile = "3.0"
duct = "0.13"
psutil = "3"
heim = "0.1.0-rc.1"
envfile = "0.2"
chrono = "0.4"
gut = { version = "0.1.4", package = "gchemol-gut" }
text_parser = { version = "0.2", package = "gchemol-parser" }

[dev-dependencies]
# cargo.toml:1 ends here
